repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.12.1
  hooks:
    - id: black
      language_version: python3.11
      exclude: ^components/
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      exclude: ^components/
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
        ]
