# Light Dockerfile with not ready built dependencies (1GB vs. 7-8 GB)

## newest python version as base image
FROM python:3.11.6

#set working directory and copying files, endpoint script
COPY . .
COPY entrypoint.sh .

# show files in directory
RUN ls --recursive .

# setting config and run command
RUN chmod +x ./entrypoint.sh
ENTRYPOINT [ "/webapp/entrypoint.sh" ]

# build and run commands
## docker build -t thesis:0.1.6-small -f Dockerfile-Light .
## docker run -d --name thesis -p 80:80 thesis:0.1.6-small