# Docker image build and publish workflow
# CREDIT: Adopted from
name: Docker Build & Publish

# running on every release and on manual dispatch
on:
  workflow_dispatch:

env:
  # set the registry to the GitHub Container Registry
  REGISTRY: ghcr.io
  # set github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}:${{ github.ref }}

# jobs to run
jobs:

  # cleanup job
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    # steps to run on the job
    steps:
    - name: Delete Package Versions
      uses: actions/delete-package-versions@v5.0.0
      with: 
        package-name: 'thesis-webapp'
        package-type: 'container'
        min-versions-to-keep: 2
